### ISSUE TITLE
Cannot start TheHive (NettyTransport - failed to bind to)

### ISSUE THREAD

**Issue by martinacen** [TheHive-Project/TheHive#1016]
### Request Type
Bug 

### Work Environment
Ubuntu 18.04.2 LTS
TheHive installed by DEB

### Problem Description
Everytime I want to start TheHive, I find this problem. 
> [error] a.r.t.n.NettyTransport - failed to bind to /127.0.1.1:2552, shutting down Netty transport

For this reason I need to unistall it, install it again and it works... So, I turn my computer off but, when I switch it on and try to start TheHive again, it shows that problem. 
I would like to not reinstall it everytime!

### Steps to Reproduce
1. sudo bin/thehive -Dconfig.file=/etc/thehive/application.conf 

### Complementary information
I tried to insert into code the following:
> akka.remote.netty.tcp.hostname = "127.0.0.1"

as you suggested in another topic but I got this error:

> Oops, cannot start the server.
akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2: Bind failed because of java.net.BindException: Indirizzo già in uso

Thank you for your help!

**Comment by crackytsi** [comment]
Running TheHive as superuser is not a good idear from my point of view...
It seems that the port is still bound so binding fails. Did you check if port 2552/tcp is still open by a process? When you try to start TheHive? I had this topic in the past several times...

**Comment by martinacen** [comment]
Thanks for your answer. 
I don't know why that port is still opened but how can I check if it is?
I started only Cortex before TheHive.

**Comment by martinacen** [comment]
> Running TheHive as superuser is not a good idear from my point of view...
> It seems that the port is still bound so binding fails. Did you check if port 2552/tcp is still open by a process? When you try to start TheHive? I had this topic in the past several times...

Thanks for your answer.
I don't know why that port is still opened but how can I check if it is?
I started only Cortex before TheHive.

**Comment by crackytsi** [comment]
e.g. via: netstat -tulpen | grep 2552

**Comment by martinacen** [comment]
> netstat -tulpen | grep 2552

Thanks, let me try. See you in few minutes

**Comment by martinacen** [comment]
> e.g. via: netstat -tulpen | grep 2552

Here I am.
The result is:

> tcp6       0      0 127.0.1.1:2552          :::*                    LISTEN      999        36348      -

But I don't know how can I do now (sorry, these topics are new for me).
P.s. about superuser, unfortunately I must use sudo because if I didn't use it, I would obtain the following (same for cortex!):

> bash: bin/thehive: Permesso negato

**Comment by saadkadhi** [comment]
@martinacen it is highly likely this is not an issue with TheHive or Cortex hence it should not be discussed on GitHub.

Since TheHive was installed using a DEB package, it should start without a problem at system startup. You seem to have changed its port from the default one to `2552`, and as @crackytsi wrote, you have another process binding to that port which prevents TheHive from starting. I also insist that running TheHive as a superuser is not a good idea at all. The service startup script take care of this aspect. You can look at the [training material](https://github.com/TheHive-Project/TheHiveDocs/blob/master/training-material.md) we provide get you started.

I would highly recommend you gain some familiarity, which we expect, with Unix/Linux or asking a sysadmin in your vicinity or in Unix/Linux fora.

I am going to close this issue for now.
