### ISSUE TITLE
Include Dockerfile in root of project

### ISSUE THREAD

**Issue by milesflo** [TheHive-Project/TheHive#1222]
# Include `Dockerfile` in root of project

### Request Type
Feature Request

### Description
As part of the development and release cycle, please include the Dockerfile generated by [docker.sbt](https://github.com/TheHive-Project/TheHive/blob/master/docker.sbt) in the root of the project so that the container can be built directly from the repo itself.

Note: This is a rehash of a [previously closed issue](https://github.com/TheHive-Project/TheHive/issues/117) which I believe is worth revisiting.

**Comment by milesflo** [comment]
Made a similar request in Cortex: https://github.com/TheHive-Project/Cortex/issues/247

**Comment by ilyaglow** [comment]
Dockerfile generated by sbt won't let you build container directly from the repo itself. It just copies files that are already built into a docker image.

I [put some effort](https://github.com/ilyaglow/dockerfiles/blob/master/thehive/Dockerfile) a year ago to create one. Happily send a PR if TheHive Project's maintainers are willing to have it here though.

**Comment by milesflo** [comment]
@ilyaglow I think you should do that 👍

**Comment by To-om** [comment]
@ilyaglow great job for your Dockerfile. You don't need to install sbt as TheHive comes with a wrapper (`./sbt`). You should also remove all java local cache (`~/.m2`, `~/.ivy2` and `~/.sbt`). Send a PR and put dockerfile in `package/docker` folder, I will merge the PR. But keep in mind that official docker image will still be generated by sbt, not your file.

**Comment by To-om** [comment]
Thanks  @ilyaglow

**Comment by ilyaglow** [comment]
Awesome! Recently I've improved it [a little more](https://github.com/ilyaglow/TheHive/commit/600adf9236b4e64d63b4fe0365729eda1c226e3a#diff-3d67b373d6192f1ceae0b97365e07d50R5) (and was going to send a PR but had not enough time), so the image could be built like this:
```
docker build -t thehive 'https://github.com/ilyaglow/TheHive.git#add-dockerfile' -f docker/thehive/Dockerfile
```
With your recent commit you can build TheHive repo like that too, but it clones the repo twice: first on the `docker build` and second on the `git clone` [inside the Dockerfile](https://github.com/TheHive-Project/TheHive/commit/41f1c9b71bf69825fdef8842a59016fe11040eb7#diff-7d0cd3fcd9387981b15647ca0964c65bR24), which is unnecessary since we obviously already have the repo on disk. So, the `COPY` approach will eliminate this and as a consequence speed up build time a little.

Also, it allows users to build container for any chosen branch that has this dockerfile without even using docker build args because it always copy current git context. As a downside, it doesn't allow us (or it won't be straightforward) to build an older version of TheHive repo. 

Just something to probably consider.
