### ISSUE TITLE
Do we have logic to know whether the alert is a duplicate?

### ISSUE THREAD

**Issue by dibas830** [TheHive-Project/TheHive#1302]
Do we have logic/code to know whether the alert is a duplicate? I am facing issue with duplicate alerts coming from same source. I am doing automation via API with python.

**Comment by nadouani** [comment]
When do you consider an Alert as `duplicate` in your process?

**Comment by dibas830** [comment]
In our automation code, we have integrated crowdstrike to thehive. Here when any "detection" is found, the code is being triggered and thehive will create an alert.  Again, when we trigger the same code, it is creating a duplicate alert for same “detection” of crowdstrike. 
Here I mean to say, for a single "detection" we can create multiple alerts which are duplicate. This is the same for "case" as well. Do we have logic to know whether the alert is a duplicate?

**Comment by nadouani** [comment]
It's your work to filter what you send to TheHive. If you send alerts that already exist then you are doing it wrong.

TheHive use the combination of `type`, `source` and `sourceRef` fields in alert as unique.

**Comment by dibas830** [comment]
![image](https://user-images.githubusercontent.com/60923089/81171772-9c77b000-8fba-11ea-9509-b46fe9e28475.png)

Kindly refer to the attached snapshot. We are getting two different alerts for same detection . It is happened , after triggering to the code. Here question is, how can we avoid duplicate alert if it is already created for a detection.

**Comment by crackytsi** [comment]
This is expected.
An Alert is a new Alert if (Source-)Reference, Type and Source are different to an existing one.
So that means, If you have 2 Alerts that should be detected as duplicate, these 3 attributes needs to be the same.
If you would create a second alert with reference cc6ca2 ths would fail,because of duplicate.
You can see this also in the TheHive Documentation about alerts.

So thats the way TheHive works, it might have consequences for your implementation / Alert feeder.
The Alert-Title is not a relevant field for detecting duplicate Alerts. An Alert name could potentially change if an Alert gets updated. Relevant are the mentioned 3 attributes.

**Comment by nadouani** [comment]
`sourceRef` is supposed to be a unique identifier of an alert in the original alert provider, in your case, Crowdstrike. I think you are generating a random `sourceRef` in your case.
