### ISSUE TITLE
[Bug] Attachment.* filters are broken under observable search in v4.0.1 

### ISSUE THREAD

**Issue by KaanSK** [TheHive-Project/TheHive#1649]
# Attachment.* filters are broken under observable search in v4.0.1

### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| OS version (client)       | Ubuntu, Windows10
| TheHive version / git hash   | 4.0.1
| Package Type              | DEB, Docker
| Browser type & version    | All browsers

### Problem Description
Under search/observables when attachment.hashes filter is selected no field to input data can be seen. Additionally, other attachment.* filters returns "Bad Request"

### Steps to Reproduce
1. Go to search/Observables
1. Select attachment.hashes filter and observe there is no input field
1. Select any other attachment.* filters and type 'test' for searching. Observe 'Bad Request' error.

### Complementary information
![issue (2)](https://user-images.githubusercontent.com/5330275/99145977-4fb51600-267c-11eb-8806-7c9f1502980e.gif)

**Comment by nadouani** [comment]
@To-om I found the following issues:

- [ ] the `/api/describe` doesn't return the right type for `attachment.hashes` field. It returns `hash` instead of `string`
- [ ] `/api/v0/_search` used in the Search page, produces `Property attachment.size for type org.thp.scalligraph.traversal.Traversal.V[org.thp.thehive.models.Observable] not found"` for `attachment.*` fields
