### ISSUE TITLE
[Question] Find out number of elements for a specific filter

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/TheHive#1961]
### Request Type

Question

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Debian |
| OS version (client)        | 10           |
| TheHive version / git hash | 4.1.3               |
| Package Type               | DEB |

### Question
How can I find out how many open cases / closed-Cases / alerts with a specific filter etc I have if the number is > 1000?

**Comment by To-om** [comment]
In order to speed up the responsiveness, the UI currently doesn't show the information you request. You can increase the threshold by setting `query.limitedCountThreshold` in application.conf. If the value is negative, the count won't be truncated (but requests will be slower).
If you are using the API you can retrive the element count without changing the configuration.
