### ISSUE TITLE
Single-Sign On support

### ISSUE THREAD

**Issue by ppanero** [TheHive-Project/TheHive#354]
### Request Type
Feature Request

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | CentOS
| OS version (client)       | 7.4
| TheHive version / git hash   | latest
| Package Type              | RPM
| Browser type & version    | All

### Description
Single-Sign On support (e.g. Shibboleth based, ADFS backend, SAML/OAuth). I am willing to work on this and provide a PR, in case you want to have a chat about it, Im available in Gitter.

**Comment by saadkadhi** [comment]
Hi @ppanero. Thank you for the FR and your willingness to work on it. We will gladly review the PR and integrate it. @To-om will liaise with you before mid-Nov.

**Comment by ppanero** [comment]
Hello,

We are about to start on this so my questions are:
- Is there any code/start on this?
- Who should I contact to discuss details before starting?

Thanks in advance

**Comment by drewstinnett** [comment]
Hi Folks,
     Our team is definitely interested in this bit as well, specifically Shibboleth/OIDC/SAML.  We're glad to help test and/or provide input for any of these as well.

**Comment by To-om** [comment]
Hi,

In TheHive, authentication is managed by [AuthSrv](https://github.com/CERT-BDF/elastic4play/blob/master/app/org/elastic4play/services/UserSrv.scala#L43) service. The default implementation is [MultiAuthSrv](https://github.com/CERT-BDF/elastic4play/blob/master/app/org/elastic4play/services/auth/MultiAuthSrv.scala) which delegates to configured authentications ([LocalAuthSrv](https://github.com/CERT-BDF/TheHive/blob/master/thehive-backend/app/services/LocalAuthSrv.scala), [LdapAuthSrv](https://github.com/CERT-BDF/elastic4play/blob/master/app/org/elastic4play/services/auth/LdapAuthSrv.scala) or [ADAuthSrv](https://github.com/CERT-BDF/elastic4play/blob/master/app/org/elastic4play/services/auth/ADAuthSrv.scala)).

If you want to implement a new authentication provider, you must create a new service that extends AuthSrv with the some of the following members:

 - `name` name of the provider
 - `capabilities` what can the provider do (changePassword, setPassword, authByKey)
 - `authenticate` a method that takes the username, the password and the HTTP request and returns an AuthContext
 - `authenticate` a method that take a key  and the HTTP request and returns an AuthContext
 - `changePassword` change the password of an user by providing the old one
 - `setPassword` change the password of an user without providing the old one
 - `renewKey`, `getKey`, `removeKey`, self explanatory.

[AuthContext](https://github.com/CERT-BDF/elastic4play/blob/master/app/org/elastic4play/services/UserSrv.scala#L14) is a trait that is added to the request in order to give information about user who do the request.

If you want to implement SSO authentication provider, I think you will have to add a new method `authenticate` with only the HTTP request as parameter.

**Comment by saibot94** [comment]
Hello,

I'll be taking over the implementation of this feature request (me and @ppanero are work colleagues). I'm leaving this comment as a heads-up so that you don't get confused when I open the pull request.

I just need a small clarification. The code changes should be done on the `elastic4play` library, right? Since that one handles all of the other auth methods.

Thanks!

**Comment by To-om** [comment]
Hi,
If you add a standard authentication provider (AuthSrv), you can put it in Elastic4play or TheHive.
But in your case, you have to change definition of AuthSrv (to be able to authenticate a request without password nor key). So your changes must be done on elastic4play.

**Comment by legoguy1000** [comment]
Has there been any updates on SAML authentication?
