### ISSUE TITLE
When merging case, artifact TLP is merged with min TLP but should be merged with max

### ISSUE THREAD

**Issue by srilumpa** [TheHive-Project/TheHive#443]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian
| TheHive version / git hash   | 3.0.3
| Package Type              | DEB

### Problem Description
When merging two cases A and B with a common artifact, the artifact in the new case has its TLP set to `min(caseA.artifact.tlp, caseB.artifact.tlp)`. On the contrary, merging two cases will generate a case with the highest TLP of the two original cases. This logic should also be applied when merging artifacts.

### Steps to Reproduce
1. Add to an existing case (or create a new case before that) some artifact with a red (3) TLP
2. Repeat operation 1 but with a white (0) TLP
3. Merge the two cases
4. The artifact in the resulting case will have its TLP set to white (0)

### Possible Solutions
Reduce the artifacts TLP with the `max` method instead of the `min` one when merging cases.

**Comment by saadkadhi** [comment]
I do not agree. If you flag an observable TLP:WHITE in case A and TLP:RED in case B, then it must be considered TLP:WHITE upon merge, which we'll give you more flexibility to play with it, analyze it and share it. Of course, the risk is that it was miscategorized in case A hence you could end up leaking data. But TheHive won't replace good opsec procedures, team orgs and do's/don'ts.

**Comment by Rolinh** [comment]
@saadkadhi I'll remember never to share anything confidential with you :)

So if an observable was wrongly categorized *once* as TLP:WHITE, then subsequently correctly as TLP:RED, you would choose to pick the less restrictive sharing conditions because "it gives you more flexibility"? I (and I'm sure I'm not alone here) would rather pick the more restrictive sharing conditions of the two to be on the safe side and not taking the risk of leaking classified information.

And remember, "l'erreur est humaine": even someone competent may wrongly classify an observable *once* by mistake, even with "good opsec procedures, team orgs and do's/don'ts".

**Comment by srilumpa** [comment]
In my mind, it would be safer to keep the most confidential TLP. A human operator could always afterward decrease its confidentiality level if needed.

I suggested this issue simply to apply the same logic used when merging cases: when two cases are merged the merged case TLP is the highest TLP of the two original case.

**Comment by saadkadhi** [comment]
@Rolinh haha :) You got me wrong. No matter what you do, if an observable was wrongly categorised as TLP:WHITE in case A and the case A NOT merged with anything else, you still have the error right there. Counting on a potential new case where the same observable was flagged with the right TLP and wishing for the stars to align so that an analyst merge both cases to hopefully correct the TLP down the road is something I wouldn't bet on.

So again, if I create X.Y.Z.T as RED in a case and somebody else create it as WHITE in another case and down the road I figure out I was right and they were wrong, then I can ask for a free lunch and they can ask for proper training where they'd repeat "I would not leak confidential data" 7000 times per minute :). Hoping for a merge to catch that.... hmmmm.

@srilumpa the logic applicable to cases is not the same as the one we apply for the observables. A case can contain confidential information (task logs, attachments) independently of the nature of the observables it contain.

Please note that observables are created with TLP:AMBER by default (unless of course they are inherited from an alert / external source) and the operators need to make a conscious action to change that.

Prepare your rock-solid arguments folks. The debate is on and I can be quite the PITA :)

**Comment by ilyaglow** [comment]
What if analyst already ran analyzers on the artifact with `TLP:WHITE` and effectively leaked it somewhere? Or the case got exported to MISP / consumed another way and published before merging?

Sticking to max TLP here can give you a false sense of sharing boundaries that were already set before and probably impossible to undone afterwards, so I agree with @saadkadhi.
