### ISSUE TITLE
Observable value wiped on changing type field during creation

### ISSUE THREAD

**Issue by gimmic** [TheHive-Project/TheHive#507]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| TheHive version / git hash   | 3.0.5
| Package Type              | DEB
| Browser type & version    | NA

### Problem Description
When entering a new observable, if you put in the value first then go to change the observable type via the drop-down, the data input gets wiped.

### Steps to Reproduce
1. Add new Observable in a case
2. Put value in the Observable field
3. Set the type of the observable
4. Notice that the observable value is gone.

### Possible Solutions
Retain the previously input observable value when changing types. Validate on submission(or on type field change)

**Comment by nadouani** [comment]
Hello,

till now, this is not a "bug", well, wiping the data field is made on purpose, because handling file observables is different from other datatypes.

We basically thought that users will follow the form, but selecting the the type first then pasting the observables data, but it looks like this is not always true :)

I'll consider fixing this

Nabil

**Comment by nadouani** [comment]
Missed this issue, that has already been fixed
