### ISSUE TITLE
Observable IP does not check if value is an IP address

### ISSUE THREAD

**Issue by MichaelDwucet** [TheHive-Project/TheHive#510]
### Request Type
Bug

### Problem Description
When pasting a hash sum I accidentally chose "IP" as the type for the observable instead of "hash". TheHive accepted the hash sum as an IP address

### Steps to Reproduce
1. Add observable
2. Select IP
3. Type asasdasdasdafa

### Possible Solutions
Add plausibility check for IP addresses.

**Comment by Rolinh** [comment]
This is true for any observable type, not only "IP". As it is also true that any observable is "defanged", regardless of its type (see #490).

![image](https://user-images.githubusercontent.com/1324157/37698932-6dd218f6-2ce5-11e8-8262-8560dd4cf857.png)

My conclusion is that all observables are treated the same way, regardless of the type that is specified.

**Comment by nadouani** [comment]
Yes, there is no data validation when adding observables, based on datatypes.

Datatypes collection can be user defined, and admin can add new types, could rename "ip" to "ip4" or whatever, and in this case, the validation will no longer work, since it can just be hardcoded.

We've decided to let the users free/responsible for what they type.

The choice could be discussed ;)
