### ISSUE TITLE
Making dashboards private makes them "invisible"

### ISSUE THREAD

**Issue by XizzoR** [TheHive-Project/TheHive#555]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu Server 16.04
| OS version (client)       | Windows 10
| TheHive version / git hash   | 3.0.9
| Package Type              | Docker
| Browser type & version    | Chrome 65.0.3325.181

### Problem Description
Making dashboards private makes them "invisible" - you can't find them nor turn them shared again. They just disappear.

### Steps to Reproduce
1. login to TheHive as Admin and select Dashboards
2. Click blue button "Edit" on existing shared dashboard
3. Turn Visibility to Private and Update

### Possible Solutions
Fix the issue where trying to search for "private" returns only a string "Search result (X records(s) found)" where X is number of private dashboard. There is no concrete result (there should be?).

**Comment by nadouani** [comment]
Hello,

Does this apply to all the dashboads? From my tests, this is true for the "System created dashboards" because they are owned by the system user. Making them "private" means no one else their creator is allowed to see them.

The issue you describe above is not true for other user created dashboards. The rule is: a private dashboard should only be seen by it's creator.

That said, the issue you describe in "Possible solutions" is valid: dashboads should not be searchable
