### ISSUE TITLE
Improvement: Upload of observables seem to fail "silently"

### ISSUE THREAD

**Issue by vlabmichl** [TheHive-Project/TheHive#829]
### Request Type
Feature Request

### Description
As  an improvement to the UI / UX when dealing with "uploads of  observables" it would be great if the upload would "not fail silently".

In my case I offered the wrong password to a ZIP-file.

The annoying thing is that you have to "re-enter all fields" of the upload form each time you retry your upload.

Would be more convenient if the file and the according dataset were  stored on the server / database an the dataset is marked with sth like  "proccessing error" if needed. Then you'd only need fix the attributes  that might be false.

Especially when you're trying to do "Trial-and-Error" with passwords this would be nice to have. Probably related the #210 feature request is somehow similar herein as well.

;-)

**Comment by wiftey** [comment]
Not sure if itis the same issue but in my case the issue is as follows:

Open a case. 
Upload an observable, type file
Mark as zipped file, add password "malware" ( I am uploading previously download file from another hive instance)
Get the pop up "Observable successfully created
Refresh

I cannot see any observable anymore, despite it says there is one 1 (or more) observables. 

Using Chrome, running the Hive on docker

**Comment by nadouani** [comment]
Reopen this issue to fix more cases.
