### ISSUE TITLE
Add a UI configuration admin section

### ISSUE THREAD

**Issue by nadouani** [TheHive-Project/TheHive#888]
### Request Type
Feature Request

### Problem Description
The goal of this feature is to make the UI configurable using some settings that an administrator could define for all the users.

A first setting has been asked for to disable the possibility of creating empty cases from the UI (#449)

This UI config section will be incrementally improved

**Comment by nadouani** [comment]
This is a gift :)

<img width="1122" alt="screen shot 2019-02-21 at 00 22 06" src="https://user-images.githubusercontent.com/21827/53132057-cb009b00-356e-11e9-83db-451766310347.png">

**Comment by crackytsi** [comment]
@nadouani Thanks for your gift. I like it very much :-) :1st_place_medal:

**Comment by github-pba** [comment]
Nadouani,

I'd like to comment the implementation of this feature.

From a UI perspective, the label of the checkbox is (a) redundant with its title and (b) strange, because check boxes are always checked - no need to explain this

From my point of view, it would be better to only have the checkbox labelled "Hide _Empty Case_ button when creating a new case (disables creation of empty cases)
![Empty case](https://user-images.githubusercontent.com/50981940/60567699-1a4fa700-9d6b-11e9-9554-4c3c481599e9.png)
".

**Comment by nadouani** [comment]
Hello @github-pba I'd say wait and see how it looks once we will add other options other than check boxes :)
